export const importTemplate = {
  Active: 1,
  Name: "",
  categories: "",
  PriceTaxExcluded: "",
  taxRuleId: "1",
  Reference: "",
  suppliers: "",
  width: "",
  Height: "",
  depth: "",
  quantity: "999",
  visibility: "both",
  description: "",
  availableForOrder: "1",
  ProductCreationDate: "",
  showPrice: "1",
  imageURL: "",
  condition: "new",
};
